### ISSUE TITLE
Win11 - Error create SuperLauncherConfig.xml

### ISSUE THREAD

**Issue by nunorosa9** [belowaverage-org/SuperLauncher#17]
Accessing or creating shortcuts in the application causes the following erro
![2021-11-15_11-40-18](https://user-images.githubusercontent.com/69484935/141783923-2fcdc803-586d-49d1-b014-1553368902ec.png)
r.

**Comment by krisdb2009** [comment]
Can you provide the full text in the error?

**Comment by nunorosa9** [comment]
The problem is related to the variable path in settings.cs

I changed to the following path and compiled the code and it's already working:
`  private readonly string configDir = Path.Combine(@"C:\_Work\Programas\SuperLauncher\temp", Environment.UserDomainName, Environment.UserName);
        public string configPath = Path.Combine(@"C:\_Work\Programas\SuperLauncher\temp", Environment.UserDomainName, Environment.UserName, "SuperLauncherConfig.xml");`

Congratulations for the program, well done!

**Comment by krisdb2009** [comment]
Awesome, glad you got it working!
