### ISSUE TITLE
Modernize UI

### ISSUE THREAD

**Issue by krisdb2009** [belowaverage-org/SuperLauncher#18]
![Screenshot 2022-03-07 021149](https://user-images.githubusercontent.com/8226974/156984702-6c4bd27c-1b04-4751-ae64-9267ff36601d.png)

**Comment by krisdb2009** [comment]
![image](https://user-images.githubusercontent.com/8226974/164761043-7a3c3756-e717-448b-8926-68523a5d40a8.png)

**Comment by krisdb2009** [comment]
![image](https://user-images.githubusercontent.com/8226974/179451802-6f4ea6c1-6bb4-44ae-856a-e643de72c7ff.png)
![image](https://user-images.githubusercontent.com/8226974/179451861-cd47607f-1ff9-4cd9-bf78-ddb184e42021.png)
![image](https://user-images.githubusercontent.com/8226974/179451893-97e440f5-809c-4736-ab3f-841703fbd325.png)
![image](https://user-images.githubusercontent.com/8226974/179451952-50169e52-97f1-4d7a-80f0-39940f15b7ec.png)
![image](https://user-images.githubusercontent.com/8226974/179451996-086dc00a-f2ef-4ca9-a9d2-335bcd81dc22.png)

**Comment by krisdb2009** [comment]
Windows 10 theming needs to be looked at.

**Comment by MostHated** [comment]
Looks good. Is there a way to assign a shortcut combo to open it? And is there a way to make it open in the center of the screen? It seems to remember the size I make it, not the position.

**Comment by krisdb2009** [comment]
@MostHated Yep! 

Press ALT + S to open in center screen.
ALT + E opens explorer.
and ALT + R opens the run dialog.
